from __future__ import annotations

import base64
import csv
import io
import json
import math
import statistics
import sys
import textwrap
import xml.etree.ElementTree as ET
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


NOTEBOOK_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = NOTEBOOK_DIR.parents[1]
AI_ROOT = PROJECT_ROOT / "ai"
PROJECT_DATA_DIR = PROJECT_ROOT / "data"
SERVER_DATA_DIR = PROJECT_ROOT / "server" / "data"
DATA_ROOTS = [PROJECT_DATA_DIR, SERVER_DATA_DIR]
MODELS_DIRS = [root / "models" for root in DATA_ROOTS]
SUMO_DIRS = [root / "sumo" for root in DATA_ROOTS]

if str(AI_ROOT) not in sys.path:
    sys.path.insert(0, str(AI_ROOT))


try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:
    plt = None

try:
    import pandas as pd
except Exception:
    pd = None


def markdown_cell(source: str) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": split_source(source),
    }


def executed_code_cell(source: str, outputs: list[dict[str, Any]] | None = None, execution_count: int | None = None) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": execution_count,
        "metadata": {
            "jupyter": {"source_hidden": True},
            "tags": ["hide-input"],
        },
        "outputs": outputs or [],
        "source": split_source(source),
    }


def split_source(source: str) -> list[str]:
    return textwrap.dedent(source).strip().splitlines(True)


def notebook(title: str, cells: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "cells": [
            markdown_cell(
                f"""
                # {title}

                Generated by `ai/notebooks/create_analysis_notebooks.py`.

                Generated at UTC: `{datetime.now(timezone.utc).isoformat()}`

                Project root: `{PROJECT_ROOT}`

                These notebooks are generated with embedded outputs. Code cells are hidden by default in Jupyter UI metadata.
                """
            ),
            *cells,
        ],
        "metadata": {
            "kernelspec": {
                "display_name": f"Python 3 — UrbanFlow AI ({Path(sys.executable).name})",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "pygments_lexer": "ipython3",
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3,
                },
            },
            "urbanflow_ai": {
                "project_root": str(PROJECT_ROOT),
                "python_executable": sys.executable,
                "generated_at_utc": datetime.now(timezone.utc).isoformat(),
                "source_hidden": True,
                "executed_by_generator": True,
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write_notebook(name: str, title: str, cells: list[dict[str, Any]]) -> None:
    path = NOTEBOOK_DIR / name
    path.write_text(json.dumps(notebook(title, cells), indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"created {path}")


def text_output(text: str) -> dict[str, Any]:
    return {
        "output_type": "stream",
        "name": "stdout",
        "text": text.splitlines(True),
    }


def html_output(html: str) -> dict[str, Any]:
    return {
        "output_type": "display_data",
        "metadata": {},
        "data": {
            "text/html": html,
            "text/plain": strip_html(html),
        },
    }


def image_output_from_current_figure() -> dict[str, Any]:
    if plt is None:
        return text_output("matplotlib is not installed; chart image was not generated.\n")

    buffer = io.BytesIO()
    plt.tight_layout()
    plt.savefig(buffer, format="png", dpi=150, bbox_inches="tight")
    plt.close()
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")

    return {
        "output_type": "display_data",
        "metadata": {},
        "data": {
            "image/png": encoded,
            "text/plain": "<matplotlib figure>",
        },
    }


def strip_html(value: str) -> str:
    result = value.replace("<br>", "\n").replace("<br/>", "\n").replace("<br />", "\n")

    for token in [
        "<table",
        "</table>",
        "<thead>",
        "</thead>",
        "<tbody>",
        "</tbody>",
        "<tr>",
        "</tr>",
        "<th>",
        "</th>",
        "<td>",
        "</td>",
        "<h2>",
        "</h2>",
        "<h3>",
        "</h3>",
        "<p>",
        "</p>",
        "<strong>",
        "</strong>",
        "<code>",
        "</code>",
    ]:
        result = result.replace(token, " ")

    while "  " in result:
        result = result.replace("  ", " ")

    return result.strip()


def dataframe_html(rows: list[dict[str, Any]], title: str, limit: int = 80) -> dict[str, Any]:
    rows = rows[-limit:]

    if pd is not None:
        frame = pd.DataFrame(rows)
        html = f"<h2>{escape_html(title)}</h2>" + frame.to_html(index=False, escape=False)
        return html_output(html)

    html = f"<h2>{escape_html(title)}</h2>"
    html += dicts_to_html_table(rows)
    return html_output(html)


def dicts_to_html_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "<p>No rows.</p>"

    columns = list(rows[0].keys())

    html = "<table><thead><tr>"
    html += "".join(f"<th>{escape_html(str(column))}</th>" for column in columns)
    html += "</tr></thead><tbody>"

    for row in rows:
        html += "<tr>"
        for column in columns:
            html += f"<td>{escape_html(format_value(row.get(column)))}</td>"
        html += "</tr>"

    html += "</tbody></table>"
    return html


def escape_html(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def format_value(value: Any) -> str:
    if value is None:
        return "—"

    if isinstance(value, float):
        return f"{value:.4f}"

    return str(value)


def latest_file(pattern: str) -> Path | None:
    files = sorted(
        PROJECT_ROOT.glob(pattern),
        key=lambda path: path.stat().st_mtime if path.exists() else 0,
    )
    return files[-1] if files else None


def all_files(pattern: str) -> list[Path]:
    return sorted(
        PROJECT_ROOT.glob(pattern),
        key=lambda path: path.stat().st_mtime if path.exists() else 0,
    )


def latest_existing(paths: list[Path]) -> Path | None:
    candidates = [path for path in paths if path.exists()]

    if not candidates:
        return None

    return max(candidates, key=lambda path: path.stat().st_mtime)


def read_text(path: Path | None) -> str:
    if path is None or not path.exists():
        return ""

    try:
        return path.read_text(encoding="utf-8")
    except Exception as error:
        return f"Could not read {path}: {error!r}"


def read_json(path: Path | None) -> dict[str, Any]:
    if path is None or not path.exists():
        return {}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        return {"error": repr(error), "path": str(path)}


def read_csv_rows(path: Path | None) -> list[dict[str, Any]]:
    if path is None or not path.exists():
        return []

    try:
        with path.open("r", newline="", encoding="utf-8") as file:
            return list(csv.DictReader(file))
    except Exception:
        return []


def read_jsonl_rows(path: Path | None) -> list[dict[str, Any]]:
    if path is None or not path.exists():
        return []

    result: list[dict[str, Any]] = []

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line:
            continue

        try:
            result.append(json.loads(line))
        except json.JSONDecodeError:
            continue

    return result


def number_or_none(value: Any) -> float | None:
    if value is None or value == "":
        return None

    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def int_or_none(value: Any) -> int | None:
    number = number_or_none(value)

    if number is None:
        return None

    return int(number)


def normalize_numeric_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    numeric_keys = {
        "current_step",
        "current_episode",
        "current_vehicles",
        "best_reward",
        "latest_reward",
        "average_wait_time",
        "average_vehicle_wait_time",
        "congestion_score",
        "stopped_vehicles",
        "active_vehicles",
        "active_pedestrians",
        "average_speed_mps",
        "throughput",
        "tls_count",
        "route_vehicle_count",
        "route_flow_count",
        "route_person_count",
        "pt_stop_count",
        "pt_vehicle_count",
        "pt_flow_count",
        "sumo_net_tls_count",
        "tls_junction_count",
    }

    normalized: list[dict[str, Any]] = []

    for row in rows:
        item = dict(row)

        for key in numeric_keys:
            if key in item:
                item[key] = number_or_none(item.get(key))

        normalized.append(item)

    return normalized


def discover_artifacts() -> dict[str, Any]:
    debug_files = all_files("data/sumo/*/debug.txt") + all_files("server/data/sumo/*/debug.txt")
    net_files = all_files("data/sumo/*/map.net.xml") + all_files("server/data/sumo/*/map.net.xml")
    route_files = all_files("data/sumo/*/all_routes.rou.xml") + all_files("server/data/sumo/*/all_routes.rou.xml")
    config_files = all_files("data/sumo/*/simulation.sumocfg") + all_files("server/data/sumo/*/simulation.sumocfg")

    history_csv_files = all_files("data/models/**/training_history.csv") + all_files("server/data/models/**/training_history.csv")
    history_jsonl_files = all_files("data/models/**/training_history.jsonl") + all_files("server/data/models/**/training_history.jsonl")
    summary_files = all_files("data/models/**/latest_summary.json") + all_files("server/data/models/**/latest_summary.json")
    checkpoint_files = all_files("data/models/**/checkpoints/*.json") + all_files("server/data/models/**/checkpoints/*.json")
    snapshot_files = all_files("data/models/**/snapshots/*.json") + all_files("server/data/models/**/snapshots/*.json")
    metadata_files = all_files("data/models/**/*.metadata.json") + all_files("server/data/models/**/*.metadata.json")
    model_json_files = all_files("data/models/**/*.json") + all_files("server/data/models/**/*.json")
    saved_model_files = [
        path
        for path in model_json_files
        if "/saved/" in path.as_posix() and not path.name.endswith(".metadata.json")
    ]

    return {
        "debug_files": debug_files,
        "net_files": net_files,
        "route_files": route_files,
        "config_files": config_files,
        "latest_debug": latest_existing(debug_files),
        "latest_net": latest_existing(net_files),
        "latest_routes": latest_existing(route_files),
        "latest_config": latest_existing(config_files),
        "history_csv_files": history_csv_files,
        "history_jsonl_files": history_jsonl_files,
        "latest_history_csv": latest_existing(history_csv_files),
        "latest_history_jsonl": latest_existing(history_jsonl_files),
        "summary_files": summary_files,
        "latest_summary": latest_existing(summary_files),
        "checkpoint_files": checkpoint_files,
        "latest_checkpoint": latest_existing(checkpoint_files),
        "snapshot_files": snapshot_files,
        "metadata_files": metadata_files,
        "model_json_files": model_json_files,
        "saved_model_files": saved_model_files,
    }


def parse_debug_file(path: Path | None) -> dict[str, Any]:
    text = read_text(path)
    result: dict[str, Any] = {}

    for line in text.splitlines():
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()

        numeric = number_or_none(value)
        result[key] = numeric if numeric is not None else value

    result["file"] = str(path.relative_to(PROJECT_ROOT)) if path else None
    return result


def parse_sumo_tls(net_path: Path | None) -> list[dict[str, Any]]:
    if net_path is None or not net_path.exists():
        return []

    try:
        root = ET.parse(net_path).getroot()
    except ET.ParseError:
        return []

    rows: list[dict[str, Any]] = []

    for junction in root.findall("junction"):
        if junction.get("type") != "traffic_light":
            continue

        junction_id = junction.get("id", "")
        incoming_lanes = [
            lane
            for lane in junction.get("incLanes", "").split()
            if lane and not lane.startswith(":")
        ]
        internal_lanes = [
            lane
            for lane in junction.get("intLanes", "").split()
            if lane
        ]
        incoming_edges = sorted(
            {
                lane.rsplit("_", 1)[0]
                for lane in incoming_lanes
                if "_" in lane
            }
        )

        try:
            x = float(junction.get("x", "0"))
            y = float(junction.get("y", "0"))
        except ValueError:
            x = 0.0
            y = 0.0

        rows.append(
            {
                "tls_id": junction_id,
                "x": x,
                "y": y,
                "incoming_lane_count": len(incoming_lanes),
                "incoming_edge_count": len(incoming_edges),
                "internal_lane_count": len(internal_lanes),
                "incoming_edges": ",".join(incoming_edges[:12]),
            }
        )

    return rows


def count_xml_tags(path: Path | None, tag: str) -> int:
    if path is None or not path.exists():
        return 0

    try:
        root = ET.parse(path).getroot()
    except ET.ParseError:
        return 0

    return sum(1 for _ in root.iter(tag))


def sumo_artifact_counts(net_path: Path | None, routes_path: Path | None) -> dict[str, Any]:
    scenario_dir = net_path.parent if net_path else None
    pt_stops_path = scenario_dir / "public_transport.add.xml" if scenario_dir else None
    pt_routes_path = scenario_dir / "public_transport.rou.xml" if scenario_dir else None

    return {
        "route_vehicles": count_xml_tags(routes_path, "vehicle"),
        "route_flows": count_xml_tags(routes_path, "flow"),
        "route_persons": count_xml_tags(routes_path, "person"),
        "pt_bus_stops": count_xml_tags(pt_stops_path, "busStop"),
        "pt_train_stops": count_xml_tags(pt_stops_path, "trainStop"),
        "pt_vehicles": count_xml_tags(pt_routes_path, "vehicle"),
        "pt_flows": count_xml_tags(pt_routes_path, "flow"),
        "sumo_tls": len(parse_sumo_tls(net_path)),
    }


def load_all_training_history(artifacts: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for path in artifacts["history_csv_files"]:
        for row in read_csv_rows(path):
            row = dict(row)
            row["history_file"] = str(path.relative_to(PROJECT_ROOT))
            rows.append(row)

    if not rows:
        for path in artifacts["history_jsonl_files"]:
            for row in read_jsonl_rows(path):
                row = dict(row)
                row["history_file"] = str(path.relative_to(PROJECT_ROOT))
                rows.append(row)

    return normalize_numeric_rows(rows)


def load_latest_training_history(artifacts: dict[str, Any]) -> list[dict[str, Any]]:
    path = artifacts["latest_history_csv"]

    rows = read_csv_rows(path)

    if not rows:
        rows = read_jsonl_rows(artifacts["latest_history_jsonl"])

    return normalize_numeric_rows(rows)


def load_model_registry_rows(artifacts: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for path in artifacts["model_json_files"]:
        payload = read_json(path)
        latest_row = payload.get("latest_training_row", {}) if isinstance(payload.get("latest_training_row"), dict) else {}

        rows.append(
            {
                "file": str(path.relative_to(PROJECT_ROOT)),
                "kind": model_file_kind(path),
                "model_type": payload.get("model_type"),
                "model_version": payload.get("model_version"),
                "signal_scope": payload.get("signal_scope") or payload.get("metadata", {}).get("signal_scope") or latest_row.get("signal_scope"),
                "current_step": payload.get("current_step") or latest_row.get("current_step"),
                "best_reward": payload.get("best_reward") or latest_row.get("best_reward"),
                "latest_reward": payload.get("latest_reward") or latest_row.get("latest_reward"),
                "average_wait_time": payload.get("average_wait_time") or latest_row.get("average_wait_time"),
                "congestion_score": payload.get("congestion_score") or latest_row.get("congestion_score"),
                "stopped_vehicles": payload.get("stopped_vehicles") or latest_row.get("stopped_vehicles"),
                "label": payload.get("label"),
                "path": payload.get("path"),
            }
        )

    return normalize_numeric_rows(rows)


def model_file_kind(path: Path) -> str:
    text = path.as_posix()

    if path.name == "latest_summary.json":
        return "latest_summary"

    if path.name.endswith(".metadata.json"):
        return "metadata"

    if "/checkpoints/" in text:
        return "checkpoint"

    if "/snapshots/" in text:
        return "snapshot"

    if "/saved/" in text:
        return "saved_model"

    if "/exports/" in text:
        return "export"

    return "json"


def describe_artifacts(artifacts: dict[str, Any]) -> str:
    lines = [
        f"Project root: {PROJECT_ROOT}",
        f"Python executable: {sys.executable}",
        f"AI root: {AI_ROOT}",
        f"Project data dir: {PROJECT_DATA_DIR}",
        f"Server data dir: {SERVER_DATA_DIR}",
        "",
        "SUMO artifacts:",
        f"  debug files: {len(artifacts['debug_files'])}",
        f"  net files: {len(artifacts['net_files'])}",
        f"  route files: {len(artifacts['route_files'])}",
        f"  latest debug: {artifacts['latest_debug']}",
        f"  latest net: {artifacts['latest_net']}",
        "",
        "Training artifacts:",
        f"  history CSV files: {len(artifacts['history_csv_files'])}",
        f"  history JSONL files: {len(artifacts['history_jsonl_files'])}",
        f"  summaries: {len(artifacts['summary_files'])}",
        f"  checkpoints: {len(artifacts['checkpoint_files'])}",
        f"  snapshots: {len(artifacts['snapshot_files'])}",
        f"  saved models: {len(artifacts['saved_model_files'])}",
        f"  metadata files: {len(artifacts['metadata_files'])}",
        f"  latest history CSV: {artifacts['latest_history_csv']}",
        f"  latest summary: {artifacts['latest_summary']}",
        f"  latest checkpoint: {artifacts['latest_checkpoint']}",
    ]
    return "\n".join(lines) + "\n"


def stats_rows(rows: list[dict[str, Any]], columns: list[str]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []

    for column in columns:
        values = [
            float(row[column])
            for row in rows
            if row.get(column) is not None
        ]

        if not values:
            continue

        result.append(
            {
                "metric": column,
                "count": len(values),
                "min": min(values),
                "mean": statistics.mean(values),
                "median": statistics.median(values),
                "max": max(values),
                "last": values[-1],
            }
        )

    return result


def reward_config() -> dict[str, float]:
    try:
        from urbanflow_ai.config import UrbanFlowModelConfig

        config = UrbanFlowModelConfig()
        return config.reward.__dict__
    except Exception:
        return {
            "queue": 2.6,
            "wait_time": 0.095,
            "stopped": 2.2,
            "congestion": 5.0,
            "low_speed": 0.45,
            "switch_penalty": 1.4,
            "throughput_bonus": 0.25,
        }


def policy_config() -> dict[str, float]:
    try:
        from urbanflow_ai.config import UrbanFlowModelConfig

        config = UrbanFlowModelConfig()
        return config.policy.__dict__
    except Exception:
        return {
            "halted": 3.0,
            "vehicles": 1.0,
            "waiting_time": 0.04,
            "occupancy": 1.6,
            "low_speed": 0.65,
            "emergency": 7.0,
        }


def analytical_reward(
    weights: dict[str, float],
    halted: float,
    waiting_time: float,
    stopped: float,
    congestion: float,
    low_speed: float,
    average_speed: float,
    switches: float,
) -> float:
    return (
        max(0.0, average_speed) * weights.get("throughput_bonus", 0.25)
        - halted * weights.get("queue", 2.6)
        - waiting_time * weights.get("wait_time", 0.095)
        - stopped * weights.get("stopped", 2.2)
        - congestion * weights.get("congestion", 5.0)
        - low_speed * weights.get("low_speed", 0.45)
        - switches * weights.get("switch_penalty", 1.4)
    )


def plot_bar(title: str, labels: list[Any], values: list[Any], xlabel: str = "", ylabel: str = "") -> dict[str, Any]:
    if plt is None:
        return text_output(f"matplotlib is not installed; skipped chart: {title}\n")

    plt.figure(figsize=(12, 4))
    plt.bar([str(label) for label in labels], values)
    plt.xticks(rotation=45, ha="right")
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    return image_output_from_current_figure()


def plot_line(title: str, xs: list[Any], series: dict[str, list[Any]], xlabel: str = "", ylabel: str = "") -> dict[str, Any]:
    if plt is None:
        return text_output(f"matplotlib is not installed; skipped chart: {title}\n")

    plt.figure(figsize=(12, 4))

    plotted = False

    for name, ys in series.items():
        clean_x: list[Any] = []
        clean_y: list[float] = []

        for x, y in zip(xs, ys):
            if y is None:
                continue

            clean_x.append(x)
            clean_y.append(float(y))

        if not clean_x:
            continue

        plt.plot(clean_x, clean_y, marker="o", linewidth=1.6, label=name)
        plotted = True

    if plotted:
        plt.legend()

    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True, alpha=0.25)
    return image_output_from_current_figure()


def plot_hist(title: str, values: list[Any], xlabel: str = "") -> dict[str, Any]:
    if plt is None:
        return text_output(f"matplotlib is not installed; skipped chart: {title}\n")

    clean_values = [float(value) for value in values if value is not None]

    if not clean_values:
        return text_output(f"No numeric data for chart: {title}\n")

    plt.figure(figsize=(10, 4))
    plt.hist(clean_values, bins=min(30, max(5, int(math.sqrt(len(clean_values))))))
    plt.xlabel(xlabel)
    plt.ylabel("Count")
    plt.title(title)
    plt.grid(True, alpha=0.25)
    return image_output_from_current_figure()


def plot_scatter(title: str, xs: list[Any], ys: list[Any], xlabel: str, ylabel: str) -> dict[str, Any]:
    if plt is None:
        return text_output(f"matplotlib is not installed; skipped chart: {title}\n")

    clean_x: list[float] = []
    clean_y: list[float] = []

    for x, y in zip(xs, ys):
        if x is None or y is None:
            continue

        clean_x.append(float(x))
        clean_y.append(float(y))

    if not clean_x:
        return text_output(f"No numeric data for chart: {title}\n")

    plt.figure(figsize=(10, 5))
    plt.scatter(clean_x, clean_y)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True, alpha=0.25)
    return image_output_from_current_figure()


def plot_reward_surface() -> dict[str, Any]:
    if plt is None:
        return text_output("matplotlib is not installed; skipped reward surface.\n")

    weights = reward_config()
    halted_values = list(range(0, 41))
    waiting_values = list(range(0, 601, 10))
    surface: list[list[float]] = []

    for waiting_time in waiting_values:
        row = []

        for halted in halted_values:
            row.append(
                analytical_reward(
                    weights=weights,
                    halted=halted,
                    waiting_time=waiting_time,
                    stopped=halted,
                    congestion=halted * 0.2,
                    low_speed=halted * 0.25,
                    average_speed=max(0.0, 12.0 - halted * 0.2),
                    switches=1,
                )
            )

        surface.append(row)

    plt.figure(figsize=(11, 6))
    plt.imshow(
        surface,
        origin="lower",
        aspect="auto",
        extent=[min(halted_values), max(halted_values), min(waiting_values), max(waiting_values)],
    )
    plt.colorbar(label="Reward")
    plt.xlabel("Halted vehicles")
    plt.ylabel("Total waiting time, seconds")
    plt.title("Reward surface: queue vs waiting time")
    return image_output_from_current_figure()


def rolling_average(values: list[Any], window: int) -> list[float | None]:
    result: list[float | None] = []
    clean: list[float] = []

    for value in values:
        numeric = number_or_none(value)

        if numeric is None:
            result.append(None)
            continue

        clean.append(numeric)
        result.append(statistics.mean(clean[-window:]))

    return result


def metric_values(rows: list[dict[str, Any]], key: str) -> list[Any]:
    return [row.get(key) for row in rows]


def build_01_explore_sumo_tls() -> list[dict[str, Any]]:
    artifacts = discover_artifacts()
    debug_payload = parse_debug_file(artifacts["latest_debug"])
    tls_rows = parse_sumo_tls(artifacts["latest_net"])
    counts = sumo_artifact_counts(artifacts["latest_net"], artifacts["latest_routes"])
    model_rows = load_model_registry_rows(artifacts)
    history_rows = load_latest_training_history(artifacts)

    outputs: list[dict[str, Any]] = [
        text_output(describe_artifacts(artifacts)),
        html_output("<h2>Latest SUMO debug.txt</h2><pre>" + escape_html(read_text(artifacts["latest_debug"])) + "</pre>"),
        dataframe_html([debug_payload], "Parsed latest SUMO debug metrics", limit=10),
        dataframe_html(sorted(tls_rows, key=lambda row: row["incoming_lane_count"], reverse=True), "Top SUMO traffic lights by incoming lane complexity", limit=50),
        plot_bar(
            "SUMO scenario artifact counts",
            list(counts.keys()),
            list(counts.values()),
            ylabel="Count",
        ),
    ]

    if tls_rows:
        incoming_lane_counts = [row["incoming_lane_count"] for row in tls_rows]
        incoming_edge_counts = [row["incoming_edge_count"] for row in tls_rows]

        edge_distribution = Counter(incoming_edge_counts)
        lane_distribution = Counter(incoming_lane_counts)

        outputs.extend(
            [
                plot_bar(
                    "Traffic lights by incoming edge count",
                    list(edge_distribution.keys()),
                    list(edge_distribution.values()),
                    xlabel="Incoming edge count",
                    ylabel="Traffic lights",
                ),
                plot_bar(
                    "Traffic lights by incoming lane count",
                    list(lane_distribution.keys()),
                    list(lane_distribution.values()),
                    xlabel="Incoming lane count",
                    ylabel="Traffic lights",
                ),
                plot_scatter(
                    "Traffic-light complexity scatter",
                    incoming_edge_counts,
                    incoming_lane_counts,
                    xlabel="Incoming edges",
                    ylabel="Incoming lanes",
                ),
                plot_hist(
                    "Traffic-light incoming lane histogram",
                    incoming_lane_counts,
                    xlabel="Incoming lanes",
                ),
            ]
        )

    outputs.extend(
        [
            dataframe_html(stats_rows(tls_rows, ["incoming_lane_count", "incoming_edge_count", "internal_lane_count"]), "SUMO TLS descriptive statistics", limit=100),
            dataframe_html(model_rows, "Local model registry and checkpoint files", limit=80),
            dataframe_html(history_rows, "Latest AI training history", limit=80),
        ]
    )

    if history_rows:
        xs = metric_values(history_rows, "current_step")
        outputs.extend(
            [
                plot_line(
                    "AI training reward history",
                    xs,
                    {
                        "latest_reward": metric_values(history_rows, "latest_reward"),
                        "best_reward": metric_values(history_rows, "best_reward"),
                    },
                    xlabel="Training step",
                    ylabel="Reward",
                ),
                plot_line(
                    "AI training traffic metrics",
                    xs,
                    {
                        "average_wait_time": metric_values(history_rows, "average_wait_time"),
                        "congestion_score": metric_values(history_rows, "congestion_score"),
                        "stopped_vehicles": metric_values(history_rows, "stopped_vehicles"),
                    },
                    xlabel="Training step",
                ),
            ]
        )

    return [
        markdown_cell(
            """
            ## Executed SUMO and AI artifact overview

            This notebook was generated with embedded outputs. It reads real generated files only.
            """
        ),
        executed_code_cell(
            "# UrbanFlow AI generated SUMO/TLS report. Outputs are embedded by create_analysis_notebooks.py.\n",
            outputs,
            execution_count=1,
        ),
    ]


def build_02_reward_design() -> list[dict[str, Any]]:
    artifacts = discover_artifacts()
    history_rows = load_latest_training_history(artifacts)
    weights = reward_config()
    policy_weights = policy_config()

    sensitivity_rows: list[dict[str, Any]] = []

    for halted in [0, 2, 5, 10, 20, 40]:
        sensitivity_rows.append(
            {
                "scenario": f"halted={halted}",
                "halted": halted,
                "waiting_time": 0,
                "congestion": 0,
                "switches": 0,
                "reward": analytical_reward(weights, halted, 0, halted, 0, 0, 10, 0),
            }
        )

    for waiting_time in [0, 30, 60, 120, 300, 600]:
        sensitivity_rows.append(
            {
                "scenario": f"waiting_time={waiting_time}",
                "halted": 0,
                "waiting_time": waiting_time,
                "congestion": 0,
                "switches": 0,
                "reward": analytical_reward(weights, 0, waiting_time, 0, 0, 0, 10, 0),
            }
        )

    for congestion in [0, 1, 2, 5, 10, 20]:
        sensitivity_rows.append(
            {
                "scenario": f"congestion={congestion}",
                "halted": 0,
                "waiting_time": 0,
                "congestion": congestion,
                "switches": 0,
                "reward": analytical_reward(weights, 0, 0, 0, congestion, 0, 10, 0),
            }
        )

    for switches in [0, 1, 2, 5, 10, 20]:
        sensitivity_rows.append(
            {
                "scenario": f"switches={switches}",
                "halted": 0,
                "waiting_time": 0,
                "congestion": 0,
                "switches": switches,
                "reward": analytical_reward(weights, 0, 0, 0, 0, 0, 10, switches),
            }
        )

    phase_rows = []

    for name, halted, vehicles, waiting_time, occupancy, low_speed, emergency in [
        ("empty approach", 0, 0, 0, 0, 0, 0),
        ("moving traffic", 0, 12, 15, 0.3, 1, 0),
        ("short queue", 4, 10, 60, 0.4, 4, 0),
        ("long queue", 18, 25, 260, 0.9, 18, 0),
        ("emergency approach", 2, 6, 30, 0.2, 2, 1),
    ]:
        pressure = (
            halted * policy_weights.get("halted", 3.0)
            + vehicles * policy_weights.get("vehicles", 1.0)
            + waiting_time * policy_weights.get("waiting_time", 0.04)
            + occupancy * policy_weights.get("occupancy", 1.6)
            + low_speed * policy_weights.get("low_speed", 0.65)
            + emergency * policy_weights.get("emergency", 7.0)
        )

        phase_rows.append(
            {
                "phase": name,
                "halted": halted,
                "vehicles": vehicles,
                "waiting_time": waiting_time,
                "occupancy": occupancy,
                "low_speed": low_speed,
                "emergency": emergency,
                "pressure": pressure,
            }
        )

    outputs: list[dict[str, Any]] = [
        html_output("<h2>Reward weights</h2>" + dicts_to_html_table([weights])),
        html_output("<h2>Policy pressure weights</h2>" + dicts_to_html_table([policy_weights])),
        dataframe_html(sensitivity_rows, "Reward sensitivity table", limit=100),
        plot_line(
            "Reward sensitivity: halted vehicles",
            list(range(0, 51, 2)),
            {
                "reward": [
                    analytical_reward(weights, x, 0, x, 0, 0, 10, 0)
                    for x in range(0, 51, 2)
                ]
            },
            xlabel="Halted vehicles",
            ylabel="Reward",
        ),
        plot_line(
            "Reward sensitivity: waiting time",
            list(range(0, 601, 20)),
            {
                "reward": [
                    analytical_reward(weights, 0, x, 0, 0, 0, 10, 0)
                    for x in range(0, 601, 20)
                ]
            },
            xlabel="Waiting time seconds",
            ylabel="Reward",
        ),
        plot_line(
            "Reward sensitivity: congestion",
            [x / 10 for x in range(0, 101)],
            {
                "reward": [
                    analytical_reward(weights, 0, 0, 0, x / 10, 0, 10, 0)
                    for x in range(0, 101)
                ]
            },
            xlabel="Congestion pressure",
            ylabel="Reward",
        ),
        plot_line(
            "Reward sensitivity: phase switches",
            list(range(0, 31)),
            {
                "reward": [
                    analytical_reward(weights, 0, 0, 0, 0, 0, 10, x)
                    for x in range(0, 31)
                ]
            },
            xlabel="Switches",
            ylabel="Reward",
        ),
        plot_reward_surface(),
        dataframe_html(phase_rows, "Traffic-light phase pressure examples", limit=20),
        plot_bar(
            "Phase pressure examples",
            [row["phase"] for row in phase_rows],
            [row["pressure"] for row in phase_rows],
            ylabel="Pressure",
        ),
        dataframe_html(history_rows, "Real latest training history", limit=80),
    ]

    if history_rows:
        xs = metric_values(history_rows, "current_step")
        outputs.extend(
            [
                plot_line(
                    "Real reward history from training artifacts",
                    xs,
                    {
                        "latest_reward": metric_values(history_rows, "latest_reward"),
                        "best_reward": metric_values(history_rows, "best_reward"),
                    },
                    xlabel="Training step",
                    ylabel="Reward",
                ),
                plot_scatter(
                    "Reward vs average waiting time",
                    metric_values(history_rows, "average_wait_time"),
                    metric_values(history_rows, "latest_reward"),
                    xlabel="Average wait time",
                    ylabel="Latest reward",
                ),
                plot_scatter(
                    "Reward vs congestion score",
                    metric_values(history_rows, "congestion_score"),
                    metric_values(history_rows, "latest_reward"),
                    xlabel="Congestion score",
                    ylabel="Latest reward",
                ),
            ]
        )

    checkpoint_payload = read_json(artifacts["latest_checkpoint"])

    outputs.append(
        html_output(
            "<h2>Latest checkpoint summary</h2><pre>"
            + escape_html(json.dumps(checkpoint_payload, indent=2, ensure_ascii=False)[:12000])
            + "</pre>"
        )
    )

    return [
        markdown_cell(
            """
            ## Executed reward and policy analysis

            This notebook combines deterministic reward analysis with real UrbanFlow AI training artifacts.
            """
        ),
        executed_code_cell(
            "# UrbanFlow AI generated reward-design report. Outputs are embedded by create_analysis_notebooks.py.\n",
            outputs,
            execution_count=1,
        ),
    ]


def build_03_train_tls_agent() -> list[dict[str, Any]]:
    artifacts = discover_artifacts()
    latest_history = load_latest_training_history(artifacts)
    all_history = load_all_training_history(artifacts)
    checkpoint_rows = []

    for path in artifacts["checkpoint_files"]:
        payload = read_json(path)
        checkpoint_rows.append(
            {
                "file": str(path.relative_to(PROJECT_ROOT)),
                "signal_scope": payload.get("signal_scope") or payload.get("metadata", {}).get("signal_scope"),
                "current_step": payload.get("current_step"),
                "current_episode": payload.get("current_episode"),
                "current_vehicles": payload.get("current_vehicles"),
                "best_reward": payload.get("best_reward"),
                "latest_reward": payload.get("latest_reward"),
                "average_wait_time": payload.get("average_wait_time"),
                "congestion_score": payload.get("congestion_score"),
                "stopped_vehicles": payload.get("stopped_vehicles"),
            }
        )

    checkpoint_rows = normalize_numeric_rows(checkpoint_rows)

    outputs: list[dict[str, Any]] = [
        text_output(describe_artifacts(artifacts)),
        dataframe_html(latest_history, "Latest training run history", limit=100),
        dataframe_html(all_history, "All training history rows", limit=120),
        dataframe_html(stats_rows(latest_history, ["latest_reward", "best_reward", "average_wait_time", "congestion_score", "stopped_vehicles", "current_vehicles"]), "Latest training descriptive statistics", limit=100),
        dataframe_html(checkpoint_rows, "Checkpoint files", limit=120),
    ]

    if latest_history:
        xs = metric_values(latest_history, "current_step")
        window = min(20, max(2, len(latest_history) // 5))

        outputs.extend(
            [
                plot_line(
                    "Training reward curve",
                    xs,
                    {
                        "latest_reward": metric_values(latest_history, "latest_reward"),
                        "best_reward": metric_values(latest_history, "best_reward"),
                    },
                    xlabel="Training step",
                    ylabel="Reward",
                ),
                plot_line(
                    "Training rolling reward curve",
                    xs,
                    {
                        f"latest_reward rolling {window}": rolling_average(metric_values(latest_history, "latest_reward"), window),
                        f"best_reward rolling {window}": rolling_average(metric_values(latest_history, "best_reward"), window),
                    },
                    xlabel="Training step",
                    ylabel="Reward",
                ),
                plot_line(
                    "Training vehicle difficulty",
                    xs,
                    {
                        "current_vehicles": metric_values(latest_history, "current_vehicles"),
                    },
                    xlabel="Training step",
                    ylabel="Vehicles",
                ),
                plot_line(
                    "Traffic metrics during training",
                    xs,
                    {
                        "average_wait_time": metric_values(latest_history, "average_wait_time"),
                        "congestion_score": metric_values(latest_history, "congestion_score"),
                        "stopped_vehicles": metric_values(latest_history, "stopped_vehicles"),
                    },
                    xlabel="Training step",
                ),
                plot_line(
                    "Rolling traffic metrics",
                    xs,
                    {
                        f"average_wait_time rolling {window}": rolling_average(metric_values(latest_history, "average_wait_time"), window),
                        f"congestion_score rolling {window}": rolling_average(metric_values(latest_history, "congestion_score"), window),
                        f"stopped_vehicles rolling {window}": rolling_average(metric_values(latest_history, "stopped_vehicles"), window),
                    },
                    xlabel="Training step",
                ),
                plot_hist(
                    "Latest reward distribution",
                    metric_values(latest_history, "latest_reward"),
                    xlabel="Latest reward",
                ),
                plot_hist(
                    "Average wait time distribution",
                    metric_values(latest_history, "average_wait_time"),
                    xlabel="Average wait time",
                ),
                plot_scatter(
                    "Stopped vehicles vs congestion",
                    metric_values(latest_history, "stopped_vehicles"),
                    metric_values(latest_history, "congestion_score"),
                    xlabel="Stopped vehicles",
                    ylabel="Congestion score",
                ),
            ]
        )

    if all_history:
        scope_counter = Counter(str(row.get("signal_scope")) for row in all_history)
        outputs.append(
            plot_bar(
                "Training rows by signal scope",
                list(scope_counter.keys()),
                list(scope_counter.values()),
                ylabel="Rows",
            )
        )

    return [
        markdown_cell(
            """
            ## Executed training monitor

            This notebook is rebuilt with embedded outputs after each generator run.
            """
        ),
        executed_code_cell(
            "# UrbanFlow AI generated training monitor. Outputs are embedded by create_analysis_notebooks.py.\n",
            outputs,
            execution_count=1,
        ),
    ]


def build_04_evaluate_tls_agent() -> list[dict[str, Any]]:
    artifacts = discover_artifacts()
    model_rows = load_model_registry_rows(artifacts)
    all_history = load_all_training_history(artifacts)
    saved_model_payloads = []

    for path in artifacts["saved_model_files"]:
        payload = read_json(path)
        saved_model_payloads.append(
            {
                "file": str(path.relative_to(PROJECT_ROOT)),
                "model_type": payload.get("model_type"),
                "model_version": payload.get("model_version"),
                "training_steps": payload.get("training_steps"),
                "best_reward": payload.get("best_reward"),
                "loaded_model_path": payload.get("loaded_model_path"),
                "signal_scope": payload.get("signal_scope") or payload.get("metadata", {}).get("signal_scope"),
            }
        )

    saved_model_payloads = normalize_numeric_rows(saved_model_payloads)

    outputs: list[dict[str, Any]] = [
        dataframe_html(model_rows, "All model registry files", limit=160),
        dataframe_html(saved_model_payloads, "Saved runtime model checkpoints", limit=80),
        dataframe_html(all_history, "All training history", limit=150),
    ]

    for metric in ["best_reward", "latest_reward", "average_wait_time", "congestion_score", "stopped_vehicles", "current_vehicles"]:
        metric_rows = [row for row in model_rows if row.get(metric) is not None]

        if not metric_rows:
            continue

        labels = [
            f"{row.get('signal_scope') or 'unknown'} / {row.get('kind')}"
            for row in metric_rows[-40:]
        ]
        values = [row.get(metric) for row in metric_rows[-40:]]

        outputs.append(
            plot_bar(
                f"Model artifact comparison: {metric}",
                labels,
                values,
                ylabel=metric,
            )
        )

    if all_history:
        scopes = sorted({str(row.get("signal_scope")) for row in all_history if row.get("signal_scope") is not None})

        for metric in ["latest_reward", "best_reward", "average_wait_time", "congestion_score", "stopped_vehicles"]:
            series: dict[str, list[Any]] = {}
            xs_by_scope: dict[str, list[Any]] = {}

            for scope in scopes:
                scope_rows = [
                    row
                    for row in all_history
                    if str(row.get("signal_scope")) == scope and row.get("current_step") is not None
                ]
                scope_rows.sort(key=lambda row: float(row.get("current_step") or 0))

                if not scope_rows:
                    continue

                xs_by_scope[scope] = metric_values(scope_rows, "current_step")
                series[scope] = metric_values(scope_rows, metric)

            if series:
                if len(series) == 1:
                    only_scope = next(iter(series))
                    outputs.append(
                        plot_line(
                            f"Training evaluation: {metric} ({only_scope})",
                            xs_by_scope[only_scope],
                            {only_scope: series[only_scope]},
                            xlabel="Training step",
                            ylabel=metric,
                        )
                    )
                else:
                    for scope, values in series.items():
                        outputs.append(
                            plot_line(
                                f"Training evaluation by scope: {metric} / {scope}",
                                xs_by_scope[scope],
                                {scope: values},
                                xlabel="Training step",
                                ylabel=metric,
                            )
                        )

        outputs.extend(
            [
                plot_scatter(
                    "Evaluation scatter: reward vs wait time",
                    metric_values(all_history, "average_wait_time"),
                    metric_values(all_history, "latest_reward"),
                    xlabel="Average wait time",
                    ylabel="Latest reward",
                ),
                plot_scatter(
                    "Evaluation scatter: reward vs stopped vehicles",
                    metric_values(all_history, "stopped_vehicles"),
                    metric_values(all_history, "latest_reward"),
                    xlabel="Stopped vehicles",
                    ylabel="Latest reward",
                ),
                plot_scatter(
                    "Evaluation scatter: reward vs congestion",
                    metric_values(all_history, "congestion_score"),
                    metric_values(all_history, "latest_reward"),
                    xlabel="Congestion score",
                    ylabel="Latest reward",
                ),
            ]
        )

    latest_summary = read_json(artifacts["latest_summary"])
    latest_checkpoint = read_json(artifacts["latest_checkpoint"])

    outputs.extend(
        [
            html_output("<h2>Latest summary JSON</h2><pre>" + escape_html(json.dumps(latest_summary, indent=2, ensure_ascii=False)[:12000]) + "</pre>"),
            html_output("<h2>Latest checkpoint JSON</h2><pre>" + escape_html(json.dumps(latest_checkpoint, indent=2, ensure_ascii=False)[:12000]) + "</pre>"),
        ]
    )

    return [
        markdown_cell(
            """
            ## Executed evaluation dashboard

            This dashboard compares saved artifacts, checkpoints and training histories.
            """
        ),
        executed_code_cell(
            "# UrbanFlow AI generated evaluation dashboard. Outputs are embedded by create_analysis_notebooks.py.\n",
            outputs,
            execution_count=1,
        ),
    ]


def main() -> None:
    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Project root: {PROJECT_ROOT}")
    print(f"Python executable: {sys.executable}")
    print(f"Notebook dir: {NOTEBOOK_DIR}")

    write_notebook(
        "01_explore_sumo_tls.ipynb",
        "UrbanFlow AI — Executed SUMO and TLS Exploration",
        build_01_explore_sumo_tls(),
    )
    write_notebook(
        "02_reward_design.ipynb",
        "UrbanFlow AI — Executed Reward Design Laboratory",
        build_02_reward_design(),
    )
    write_notebook(
        "03_train_tls_agent.ipynb",
        "UrbanFlow AI — Executed Training Monitor",
        build_03_train_tls_agent(),
    )
    write_notebook(
        "04_evaluate_tls_agent.ipynb",
        "UrbanFlow AI — Executed Evaluation Dashboard",
        build_04_evaluate_tls_agent(),
    )

    print("")
    print("Done. Open ai/notebooks/*.ipynb to see generated tables and charts with hidden code cells.")


if __name__ == "__main__":
    main()